version: "3"
services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
